### ISSUE TITLE
The current page isn't highlighted in the menu

### ISSUE THREAD

**Issue by PragTob** [shoes/shoesrb.com#18]
It's been bugging me for a while: In the top navigation bar Home is always highlighted, no matter what page you're on.

That's a pretty tiny thing to fix I guess :-)

**Comment by steveklabnik** [comment]
Ha! yes.

**Comment by wpp** [comment]
Damnit :) Not on computer, I guess bootstrap.js might not be included...I'll take a look as soon as I can

**Comment by wasnotrice** [comment]
I remember there's something wrong with the indentation in the <head> tag. Some haml is not getting rendered. Might be related.

**Comment by steveklabnik** [comment]
No, the issue is https://github.com/shoes/shoesrb.com/blob/master/views/layout.html.haml#L41 . It's hard-coded for Home.

**Comment by wasnotrice** [comment]
That'll do it. You can see on that github render the mis-indented haml, though. It's not syntax highlighted.
