### ISSUE TITLE
Reporting Issues

### ISSUE THREAD

**Issue by PragTob** [shoes/shoesrb.com#21]
The website should give some hint about where to report issues I think.

I'm thinking about an `issues` or `report an issue` entry in the main menu that either goes to..
- the github issues of the current default implementation
- a list of issue links from popular implementations
- maybe also includes poitners to the mailing list and IRC - it should or could rather be called `need help?` then

What do you think, what should work best?

**Comment by steveklabnik** [comment]
:+1:

**Comment by davorb** [comment]
A link to the github issues seems like a bad idea. People sometimes pop in on IRC to ask questions, but they usually leave before someone has had a chance to answer them.

**Comment by wpp** [comment]
I also think gh issues could send a lot of "how do you" type of questions here. What about stackoverflow? Just explain that they should tag their questions with "shoes".

**Comment by PragTob** [comment]
@davorb I don't get why a link to github issues is bad when people don't get answers in IRC? Or did you mean IRC?

Ok so then I'd be for a menu item like "get help" where we'd put in links to the mailing list, stackoverflow and github issues. And perhaps to the tutorials once more. Explaining that stackoverflow and the ML are more for "How do you?" questions and github issues better for bugs/feature requests.

**Comment by davorb** [comment]
@PragTob I meant IRC.

I think that what you're suggesting sounds good.

**Comment by PragTob** [comment]
@davorb then I get it and agree :-)

Happy holidays everyone! =)

**Comment by PragTob** [comment]
I see this is in as well, thanks @jamesaanderson !
