### ISSUE TITLE
Hash syntax

### ISSUE THREAD

**Issue by jamesaanderson** [shoes/shoesrb.com#25]
At the moment, there's a combination of ruby 1.8 and ruby 1.9 hash syntax in shoesrb.com. Should we convert all the 1.8 hash syntax to the 1.9 syntax? If so, I have a pull request ready.

**Comment by PragTob** [comment]
Hi there,

personally I prefer the 1.9 hash syntax so I'm all for it. However it's not something really important to change in my eyes :-)

Just open the PR and if nobody has some argument against it we'll merge it!

Thanks!
Tobi

**Comment by steveklabnik** [comment]
Yeah, I'm in the habit of 1.8, but we only deploy to 1.9, so it's fine. Merged.
