### ISSUE TITLE
Download links broken

### ISSUE THREAD

**Issue by jamesaanderson** [shoes/shoesrb.com#27]
The downloads on http://shoesrb.com/downloads.html return 404s.

**Comment by wasnotrice** [comment]
Thanks. That makes sense. They were dynamic redirects, so that we could publish URLs that didn't change. This might be the one element that gives us trouble on a static site (where we don't control the server

**Comment by jamesaanderson** [comment]
Can't that be done in JavaScript?

**Comment by steveklabnik** [comment]
Only if they click the link, not if they visit it.

**Comment by jrgifford** [comment]
And we can't do redirects on the http level with GitHub pages …

**Comment by jhirbour** [comment]
So... what's the link for the DMG (os x) in the mean time?

**Comment by jamesaanderson** [comment]
@jhirbour https://github.com/shoes/shoes/downloads

**Comment by PragTob** [comment]
Fixed via hard coded links in 51ca83ff1534d769aaa78b94e1ca5fb1015b9212
Better those than none.

For discussing possibilities of a redirect I will open a new issue.
