### ISSUE TITLE
State of shoesrb.com

### ISSUE THREAD

**Issue by wpp** [shoes/shoesrb.com#3]
Hello everyone,

I would :heart: to help out with shoesrb.com but I'm a little confused about the state of affairs. Would be great if someone could clear a few things up:
- What is the purpose of this repository? 
  - Should it eventually replace the current shoesrb.com website?
  - If so, what are the golas for the new website (is there another issue/milestone tracker)? 
- What is the purpose of https://github.com/shoes/shoes-web? Is the project deprecated?

Finally:
- I'll probably be able to figure out how to get this projects index.html to display in my browser but it would be nice if you could save me a few hours of reading :smile:

**Comment by steveklabnik** [comment]
shoes-web is a copy of redmine that is the current shoesrb.com. This repository was supposed to be the new site for Shoes, but it kinda never got finished. Everyone got really involved in actually building Shoes 4.

The goals are 'build a baller website.' Anyone who wants to do the work can interpret that as they will, though I reserve the right to veto styles I think are ugly. ;) The current site is not very good looking.

**Comment by PragTob** [comment]
Hi there,

from my current understanding this is meant to replace the current shoesrb.com - which at the latest we want to do with the release of [shoes4](https://github.com/shoes/shoes4).

And I wanted to ping @steveklabnik but I see he just showed... dunno how to start this site right now but Steve should know - I don't have the code atm and little time.

I'd really welcome work on this site :-)

Cheers,
Tobi

**Comment by steveklabnik** [comment]
Like any ruby project:

```
$ gem install bundler
$ bundle
$ rackup
```

should start it up.

**Comment by wpp** [comment]
Thanks for that quick reply. I'll give "building a baller website" a shot. Discussion is fine via issues?

**Comment by steveklabnik** [comment]
Yep!

**Comment by jrgifford** [comment]
To some extent, it's encouraged. :heart:

On Tuesday, January 15, 2013, Philipp wrote:

> Thanks for that quick reply. I'll give "building a baller website" a shot.
> Discussion is fine via issues?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shoes/shoesrb.com/issues/3#issuecomment-12280341.

## 

## 

James Gifford
cell: 2162238574
