### ISSUE TITLE
The shoes manual is not accessible at the moment

### ISSUE THREAD

**Issue by PragTob** [shoes/shoesrb.com#32]
The shoes manual aka the [walkthrough](http://shoesrb.com/walkthrough) is not accessible at the moment. It gives me a 404 on github pages, so I guess it is somehow related to the move to github pages.

As this is the go to place for shoes advice, I invented the new urgent tag as we should really fix this rather quickly.

**Edit:** Mosst importantly the **[manual](http://shoesrb.com/manual/Hello.html)** is down!

**Comment by wpp** [comment]
#33

**Comment by ghost** [comment]
Just letting you know even the fallowing link is down http://shoesrb.com/manual/Hello.html

**Comment by PragTob** [comment]
Argh it's not primarily the walkthrough but the [manual](http://shoesrb.com/manual/Hello.html) as psoted above which is not working.

Still an issue :-(

**Comment by jamesaanderson** [comment]
Is anyone working on this? If not, I'll give it a shot.

**Comment by PragTob** [comment]
you can do so :-) However I'll most likely also try today in a couple of hours. If it's not done by then I'll see what I can do :-)
