### ISSUE TITLE
Operating System signs

### ISSUE THREAD

**Issue by PragTob** [shoes/shoesrb.com#35]
Hi everyone,

Right now we got 4 signs for operating systems, 2 of them are Mac OSX. Can't we take a generic symbol for Mac OSX?

Plus the Linux one is Ubuntu, how about a cute little Tux?

Any ideas or objections? :-)

**Comment by jamesaanderson** [comment]
:+1:

**Comment by wpp** [comment]
Absolutely! I don't even remember why I used 2 for Mac OS. I do remember I couldn't find a "free" generic mac os symbol. (with good quality).

**Comment by jamesaanderson** [comment]
The Windows logo has also changed

**Comment by wpp** [comment]
Gentlemen, I've spend some considerable time trying to find logos…I shall now rest my efforts…It is not possible…If someone manages to find logos (for all platforms, good quality) let me know I'll gladly integrate them… :skull:

**Comment by plexus** [comment]
How about

http://commons.wikimedia.org/wiki/File:Windows_logo_-_2012.png
http://commons.wikimedia.org/wiki/File:Apple_Logo.svg
http://commons.wikimedia.org/wiki/File:Tux.svg

?

**Comment by jrgifford** [comment]
can someone look at the licensing on those before we use them?

**Comment by jamesaanderson** [comment]
The apple and the tux we're free to use. I'm not sure about the Windows logo.

**Comment by jamesaanderson** [comment]
Looks like the Windows logo is in the public domain and we'll have to credit the source of the tux.

**Comment by wpp** [comment]
- Windows logo is cool
- Like the coloured apple better
- Don't like the tux version. Its to shiny for my taste.

But Im okay with that. @jamesaanderson @jrgifford how and where should the credits for the tux go? footer?

**Comment by plexus** [comment]
there are other versions of tux on Wikimedia commons. And they're SVG files
I believe (vector graphics), easily editable with Inkscape.

**Comment by jrgifford** [comment]
yay, vector graphics!

**Comment by PragTob** [comment]
I'm ok with Tux, as long as you don't know the background story behind the look on his face :-)

**Comment by jamesaanderson** [comment]
http://commons.wikimedia.org/wiki/File:NewTux.svg is the only other tux image I was able to find on Wikimedia and it's under the same license. Why not add credit in a credits.txt or in the README?

**Comment by PragTob** [comment]
I'm not sure and not a lawyer but I guess we would have to credit it straight on the web page not in some file. I wouldn't see a problem with that other than where to credit it :-D

**Comment by wpp** [comment]
@jamesaanderson like that one. @PragTob quoting from the tux link:

>  "The copyright holder of this file, Larry Ewing, allows anyone to use it for any purpose, provided that the copyright holder is properly attributed. Redistribution, derivative work, commercial use, and all other use is permitted.
> Attribution: Larry Ewing". 

So something like "TuxLogo by Larry Ewing"

Quoting from Windows logo:

> It does not meet the threshold of originality needed for copyright protection, and is therefore in the public domain. Although it is free of copyright restrictions, this image may still be subject to other restrictions. 

This lawyer talk is making my head spin, . Does **in the public domain** take precedence over **may still be subject to other restrictions**? Same story with coloured apple logo.

**Comment by PragTob** [comment]
I think in the public domain is fine. If we are subject to other restrictions I hope that they will notify us.

I must add that I'm a notoriously positive thinking person :-D

**Comment by jrgifford** [comment]
i think that we should be able to find an icon for each respective OS that is the equivalent of "works with $OS".... maybe?

**Comment by JesseHerrick** [comment]
Why not use fontawesome icons? They're free, look nice, and I don't think they have copyright restrictions. You can also color them and resize them without them looking really crappy. 

[Windows Logo](http://fortawesome.github.io/Font-Awesome/icon/windows/)
[Apple Logo](http://fortawesome.github.io/Font-Awesome/icon/apple/)
[Linux Logo](http://fortawesome.github.io/Font-Awesome/icon/linux/)

**Comment by PragTob** [comment]
"Font Awesome is fully open source and is GPL compatible. You can use it for commercial projects, open source projects, or really just about whatever you want. "

Sounds cool. Thanks @JesseHerrick !

**Comment by JesseHerrick** [comment]
I think this issue should be closed because #43 fixes it.

**Comment by jrgifford** [comment]
Annnndddd done!
