### ISSUE TITLE
Make the difference between walkthrough, manual, book and RDoc clearer

### ISSUE THREAD

**Issue by PragTob** [shoes/shoesrb.com#37]
It could be made clearer what the difference between walkthrough, manual, book and RDoc is - e.g. the manual is a rather high level documentation of all the shoes methods, the walkthrough gets yous tarted and the book is a bit longer but teaches you all the basic concepts of shoes and how to lay out applications with it.

**Comment by wpp** [comment]
#39 

Feel free to give me notes and I'll be happy to improve further.

**Comment by PragTob** [comment]
Fixed by #39
