### ISSUE TITLE
First Home Page Iteration

### ISSUE THREAD

**Issue by wpp** [shoes/shoesrb.com#4]
Hello,

So I've had a couple of hours today and started work on the home page. Wanted to post a shot so you guys can let me know what you think about it. 

![Shoes The easiest little GUI toolkit for Ruby 2013-01-17 00-20-07](https://f.cloud.github.com/assets/942021/73166/7d25ce80-6033-11e2-8cdf-7a17c89753c8.png)

**Comment by steveklabnik** [comment]
This loooooks awesome! Forreals. I'm super happy.

**Comment by wpp** [comment]
:green_heart: Great! :green_heart: I'm not too happy with the text(s) yet, but I'm off to bed for now. I'll be working on it tomorrow again. I'll prepare a few more screenshots and submit a PR then.

**Comment by jrgifford** [comment]
:+1: :+1: :+1: :D

On Wednesday, January 16, 2013, Steve Klabnik wrote:

> This loooooks awesome! Forreals. I'm super happy.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shoes/shoesrb.com/issues/4#issuecomment-12346472.

## 

## 

James Gifford
cell: 2162238574

**Comment by wasnotrice** [comment]
@wpp looks great! Much needed. Thanks!

**Comment by davorb** [comment]
Looks great! I've posted a comment about this in #5
