### ISSUE TITLE
OSX Download link not working

### ISSUE THREAD

**Issue by spaghetticode** [shoes/shoesrb.com#67]
Hi there, this link on the website http://shoesrb.com/downloads/  is not working: http://shoes.mvmanila.com/public/shoes/shoes-3.2.15-osx-10.9.tgz

Best,

Andrea

**Comment by jasonrclark** [comment]
Thanks for the report @spaghetticode!

Looking at the directory, @ccoupe, I don't see the Mac version for 3.2.15. Believe the link is right, the file's just actually missing. What do you think?

**Comment by ccoupe** [comment]
.15 was problematic for a few folks. I've copied 14 to .15 so the link should work now.

FYI, Shoes 3.2.16 will be coming soon - a day or two.

**Comment by jasonrclark** [comment]
Thanks for getting on that @ccoupe!

Looks like you named the file http://shoes.mvmanila.com/public/shoes/shoes-3.2.15-osx.tgz, but the format for the other Mac files was http://shoes.mvmanila.com/public/shoes/shoes-3.2.14-osx-10.9.tgz so the actual link on the page is http://shoes.mvmanila.com/public/shoes/shoes-3.2.15-osx-10.9.tgz.

Do you want me to update the site to link without the `-10.9`, or did you want to move the file? I'm good either way.

**Comment by ccoupe** [comment]
I've renamed it properly. Thanks for double checking me.

**Comment by jasonrclark** [comment]
Looks great, thanks!
