### ISSUE TITLE
Regarding the contributors page

### ISSUE THREAD

**Issue by wpp** [shoes/shoesrb.com#7]
So @ashbb mentioned there are a few folks missing from the contributors page. I'm sorry about that, I just took a screen [from the shoes members page](https://github.com/shoes?tab=members). What do you think? How could can we get a list of all contributors?

**Comment by davorb** [comment]
I think rubinius does this using a script that goes through the git log. I'll see if I can hack something similar together once I get home.

**Comment by wasnotrice** [comment]
@davorb that's a great idea. We could also do it through the [github api](http://developer.github.com/v3/repos/#list-contributors)

**Comment by davorb** [comment]
Eric, that's awesome. I had no idea the Github API was that powerful. We 
might as well do it from there then, since the list doesn't update often 

## enough to warrant writing a proper script for it.

Davor Babic
davor@davor.se

Eric Watson wrote:

**Comment by wasnotrice** [comment]
Related: mpapis/gh_contributors

**Comment by wasnotrice** [comment]
Oops. Link: https://github.com/mpapis/gh_contributors

**Comment by PragTob** [comment]
Closed as it was updated in #71
