### ISSUE TITLE
Move The Shoes Tutorial Walkthrough

### ISSUE THREAD

**Issue by wpp** [shoes/shoesrb.com#8]
I would like to make https://github.com/ashbb/shoes_tutorial_walkthrough part of the actual shoes website. It feels kind of weird to me that it lives on GitHub like that. (And it might be confusing for total newcomers, looking behind the scenes like that).

**Comment by PragTob** [comment]
Good idea :+1:

**Comment by ashbb** [comment]
@wpp Good idea. Please do that. :)

**Comment by wpp** [comment]
I started moving the guide this is what it looks like for now ( **work in progress** ):

![Screen Shot 2013-02-14 at 8 04 30 PM](https://f.cloud.github.com/assets/942021/158063/510a21ae-76d9-11e2-8b4a-336b272c9bbc.png)
1. The code examples look like shit, I'm not sure if there is a gem or something we could you to get proper syntax highlighting?
2. I have an idea for moving the example pictures side by side with the code like so:

![Untitled](https://f.cloud.github.com/assets/942021/158065/58719864-76d9-11e2-99b9-a782bc58ffcf.jpg)

If you guys think its worth doing I would move the guides from markdown to .haml, because its easier for me.

**Comment by steveklabnik** [comment]
> If you guys think its worth doing I would move the guides from markdown to .haml, because its easier for me.

http://chriseppstein.github.com/blog/2010/02/08/haml-sucks-for-content/

> I'm not sure if there is a gem or something we could you to get proper syntax highlighting?

I'm sure there's something good, I'd used JS based solutions before. Markdown should highlight the code based on the language it detects. Hm.

**Comment by wpp** [comment]
@steveklabnik puh thanks for that link :)

> I'm sure there's something good, I'd used JS based solutions before. 

[I think this guy looks all right](http://google-code-prettify.googlecode.com/svn/trunk/README.html)

**Comment by wasnotrice** [comment]
> Markdown should highlight the code based on the language it detects.

Kramdown does this through Coderay

**Comment by PragTob** [comment]
The markdown highliting was always good for me and you can tell it what highliting to use with '''ruby

Thank you for your work.
