### ISSUE TITLE
broken link on the page of tutorials: the link to the RDocs

### ISSUE THREAD

**Issue by val461** [shoes/shoesrb.com#86]
Hello, I noticed a broken link on [the page of tutorials](http://shoesrb.com/tutorials/): the link to [the RDocs](http://www.rubydoc.info/github/shoes/shoes).

**Comment by jasonrclark** [comment]
Both those links look fixed, and the Shoes 4 docs are even getting generated again where they hadn't been for a while. Thanks for the nudge @Fornost461!

**Comment by val461** [comment]
You're welcome!
