### ISSUE TITLE
Bad link to Shoes website in manual

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoesrb.com#9]
See "the site of Shoes" link at http://shoesrb.com/manual/Installing.html

Link goes to heroku, should go to this site.

**Comment by steveklabnik** [comment]
It's been fixed in the repo: https://github.com/shoes/shoes/blob/develop/static/manual-en.txt#L90

Probably best just to fix it in the HTML for now; I scraped the existing manual that was up on the old site to make this one, it wasn't generated directly from the source.

**Comment by wpp** [comment]
#11 as @steveklabnik suggested just updated the html

**Comment by davorb** [comment]
Closing, as it should be working after #11
