### ISSUE TITLE
"Nobody knows shoes" link is broken

### ISSUE THREAD

**Issue by mrcnski** [shoes/shoesrb.com#90]
See title. The link to _why's guide on [this page](http://shoesrb.com/tutorials/) is broken.

**Comment by PragTob** [comment]
:wave: 

Thanks!

See shoes/shoes4#1563 - PRs welcome :)

**Comment by mrcnski** [comment]
Sure, raised #91

**Comment by PragTob** [comment]
Fixed in #91
